version: '3'
services:
  app:
    image: react:app
    container_name: react
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
       - 3000:3000
       - 35729:35729
    volumes:
       - ./:/app


