# Generated by Django 2.2.1 on 2019-05-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190511_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('status', 'created_at'), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('total_comments', 'created_at'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
