# Generated by Django 2.2.1 on 2019-05-15 13:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190512_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(blog.models.Status('Approved'), 'Approved'), (blog.models.Status('Pending'), 'Pending'), (blog.models.Status('Rejected'), 'Rejected'), (blog.models.Status('Draft'), 'Draft')], default='DR', max_length=5),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[(blog.models.Status('Approved'), 'Approved'), (blog.models.Status('Pending'), 'Pending'), (blog.models.Status('Rejected'), 'Rejected'), (blog.models.Status('Draft'), 'Draft')], default='PE', max_length=5),
        ),
    ]
