# Generated by Django 2.2.1 on 2019-05-15 16:38

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190515_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('RE', 'Rejected'), ('DR', 'Draft')], default=blog.models.Status('Pending'), max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('RE', 'Rejected'), ('DR', 'Draft')], default=blog.models.Status('Draft'), max_length=5),
        ),
    ]
